#!/bin/bash
# env-vars
#  . UID  - uid of the user. Eg: $(id -u $USER)
#  . GID  - gid of the user. Eg: $(id -g $USER)

USER=myuser
GROUP=mygroup

# if both these vars are set
# create a new user and setup his/her env
if [ "$UID" != "" ] && [ "$GID" != "" ]; then
    HOME=/home/$USER
    addgroup --gid $GID $GROUP
    adduser --disabled-password --gecos "" --gid $GID -G sudo,$GROUP \
            --uid $UID --home $HOME $USER
    mkdir -p /etc/sudoers.d
    echo "$USER ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USER
    chmod 0440 /etc/sudoers.d/$USER
    echo >> $HOME/.bashrc
    env | grep -v LS_COLORS >> $HOME/.bashrc
    ldconfig
else
    USER=root
    HOME=/$USER
fi

# vnc server related files
# NOTE: NOTE: NOTE:
# this assumes that the docker image would have been built using
# the reusables/vnc docker commands!!
if [ "$VNC_SETUP" = "1" ]; then
    mkdir $HOME/.vnc
    touch $HOME/.Xauthority $HOME/.Xresources
    cp /.xinitrc $HOME/.xinitrc
    cp /.xsession $HOME/.xsession
    chown $USER $HOME/.vnc $HOME/.Xauthority $HOME/.Xresources $HOME/.xsession
    chown $HOME/.xinitrc
fi

# run as that user
if [ "$USER" != "root" ]; then
    su - $USER -c $*
else
    exec $*
fi
