#!/usr/bin/env python
import json
import subprocess
import string
from argparse import ArgumentParser, REMAINDER
import os
import socket


class Launcher:
    def get(self, image, *args):
        output = subprocess.check_output("docker inspect %s" % image,
                                         shell=True)
        output = json.loads(output)[0]
        for a in args:
            if a not in output:
                return ""
            output = output[a]
        return output

    def getCmd(self, args):
        arr = self.get(args.image, "Config", "Cmd")
        if len(args.cmd) > 0:
            cmd = " ".join(args.cmd)
        elif len(arr) > 0:
            cmd = " ".join(arr)
        else:
            cmd = "/bin/bash"
        # single quotes around to directly pass this command to container!
        return ["'%s'" % cmd]

    def getPort(self, image):
        arr = self.get(image, "Config", "ExposedPorts")
        if len(arr) <= 0:
            return ""
        out = []
        for p in arr.keys():
            tmp = string.replace(p, "/tcp", "")
            out.append("-p %s:%s" % (tmp, tmp))
        return out

    def __getIP(self, rhost):
        out = socket.getaddrinfo("sc-netapp61", 0)
        return out[0][4][0]

    def __getNFSinfo(self):
        out = subprocess.check_output("df . | tail -n1 | awk '{print $1}'",
                                      shell=True)
        out = out.rstrip()
        (rhost, vol) = out.split(":")
        ip = self.__getIP(rhost)
        return (ip, vol)

    def getNFSmount(self, args):
        cmd = []
        if not args.nfsmount:
            return cmd
        (ip, vol) = self.__getNFSinfo()
        volumeopt = "volume-opt=o=addr=%s,vers=4,hard,timeo=600,rsize=1048576,wsize=1048576,retrans=2" % ip
        nfsopt = "volume-driver=local,dst=/work,volume-opt=type=nfs,volume-opt=device=:%s" % vol
        cmd.append("--mount")
        cmd.append("'type=volume,src=%s,%s,\"%s\"'" % (ip, nfsopt, volumeopt))
        return cmd

    def getVols(self, args):
        vols = []
        for vol in args.v:
            vols.append("-v %s" % vol)
        if not args.nopwd:
            vols.append("-v %s:/work:rw" % os.getcwd())
            vols.append("-w /work")
        return vols

    def getDns(self, args):
        dns = []
        for d in args.dns:
            dns.append("--dns %s" % d)
        return dns

    def getUser(self, args):
        out = []
        bindir = os.path.abspath(os.path.dirname(__file__))
        if args.runas == "user":
            out.append("-e UID=%d" % os.getuid())
            out.append("-v %s/exec-as.c:/exec-as.c:ro" % bindir)
            out.append("-v %s/runas.sh:/runas.sh:ro" % bindir)
            out.append("--entrypoint=/runas.sh")
        elif args.runas == "uid:gid":
            uid = os.getuid()
            gid = os.getgid()
            out.append("-u %d:%d" % (uid, gid))
        return out

    def launch(self):
        args = self.getParser().parse_args()
        # Prohibit pwd-mounting if nfsmount is set!
        if args.nfsmount:
            args.nopwd = True
        finalcmd = ["nvidia-docker", "run", "-it", "--rm"]
        finalcmd += self.getPort(args.image)
        finalcmd += self.getVols(args)
        finalcmd += self.getNFSmount(args)
        finalcmd += self.getUser(args)
        finalcmd += self.getDns(args)
        if args.ipc is not None:
            finalcmd += ["--ipc=%s" % args.ipc]
        if args.security is not None:
            finalcmd += ["--security-opt=\"%s\"" % args.security]
        finalcmd.append(args.image)
        finalcmd += self.getCmd(args)
        finalcmd = " ".join(finalcmd)
        print(finalcmd)
        subprocess.check_call(finalcmd, shell=True)
        return

    # override this method to define your custom parser
    # it'll be better to call this method from the child class as well!
    def getParser(self):
        parser = ArgumentParser(description="Wrapper to launch as current user")
        parser.add_argument("-v", default=[], action="append", type=str,
                            help="Volumes to mount. Same syntax as docker run")
        parser.add_argument("-runas", choices=["user", "root", "uid:gid"],
                            default="root", type=str,
                            help="Run as specified. Default is root. Options: "
                            "\n  user    - run as current user by switching user inside the container"
                            "\n  root    - run as root (default)"
                            "\n  uid:gid - pass the -u option to docker")
        parser.add_argument("-security", type=str, default=None,
                            help="Same as --security-opt option of docker")
        parser.add_argument("-nopwd", action="store_true", default=False,
                            help="Do not mount current dir as /work")
        parser.add_argument("-nfsmount", action="store_true", default=False,
                            help="Mount the nfs-root of current dir as /work. Implies -nopwd")
        parser.add_argument("-dns", default=[], action="append", type=str,
                            help="Pass DNS servers to be used inside container")
        parser.add_argument("-ipc", default=None, type=str,
                            help="how to use shared memory to share data between processes")
        parser.add_argument("image", help="Image to be launched")
        parser.add_argument("cmd", nargs=REMAINDER,
                            help="Command to run inside the container")
        return parser

if __name__ == "__main__":
    Launcher().launch()
